//! Restore points: cheap, local snapshots of an instance's `mods` folder.
//!
//! Updating or bulk-installing mods is the single most common way to break a
//! working instance, and the damage is silent: the game simply stops booting.
//! A snapshot is just a copy of the jar files (a few hundred MB at worst) plus
//! a small `meta.json`, so taking one before every risky operation is
//! affordable and makes "undo" a one-click action instead of a support ticket.
//!
//! Snapshots live in `<instance>/restore-points/<id>/`, where `id` is a
//! `YYYYMMDD-HHMMSS` stamp. Ids are validated before use so a crafted id can
//! never escape that directory.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{NimbusError, Result};
use crate::{instance, paths};

use super::shared::validate_instance_id;

/// Directory holding every snapshot of one instance.
const RESTORE_DIR: &str = "restore-points";
const META_FILE: &str = "meta.json";
/// Oldest snapshots beyond this count are pruned automatically. Ten covers
/// "undo the last few experiments" without silently eating tens of gigabytes.
const MAX_POINTS: usize = 10;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RestorePoint {
    /// `YYYYMMDD-HHMMSS`, also the folder name.
    pub id: String,
    /// Human label, e.g. "before updating mods".
    pub label: String,
    /// Unix seconds, so the frontend can format it in the user's locale.
    pub created_at: i64,
    pub mod_count: usize,
    pub size_bytes: u64,
    /// True when the snapshot was taken automatically before a risky action.
    pub automatic: bool,
}

/// A snapshot id is generated by us and must stay a plain timestamp: anything
/// else could contain `..` or a drive letter and write outside the instance.
fn validate_point_id(id: &str) -> Result<()> {
    let ok = id.len() == 15
        && id.as_bytes()[8] == b'-'
        && id.bytes().enumerate().all(|(i, b)| {
            if i == 8 {
                b == b'-'
            } else {
                b.is_ascii_digit()
            }
        });
    if ok {
        Ok(())
    } else {
        Err(NimbusError::Invalid(format!("bad restore point id: {id}")))
    }
}

/// `(mods dir, restore-points dir)` for a validated instance.
fn dirs(instance_id: &str) -> Result<(PathBuf, PathBuf)> {
    validate_instance_id(instance_id)?;
    let instances_dir = paths::instances_dir()?;
    let inst = instance::load(&instances_dir, instance_id)?;
    let mods_dir = inst.mods_dir(&instances_dir);
    let restore_dir = inst.dir(&instances_dir).join(RESTORE_DIR);
    Ok((mods_dir, restore_dir))
}

/// Copies every regular file (jars, `.disabled` jars, configs dropped in by
/// hand) from `src` to `dst`. Subdirectories are skipped on purpose: mod
/// loaders only read the top level, and recursing would turn a snapshot of a
/// pack with a nested cache into a multi-gigabyte copy.
fn copy_flat(src: &Path, dst: &Path) -> Result<(usize, u64)> {
    std::fs::create_dir_all(dst)?;
    let mut count = 0usize;
    let mut bytes = 0u64;
    let Ok(entries) = std::fs::read_dir(src) else {
        return Ok((0, 0));
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name() else {
            continue;
        };
        std::fs::copy(&path, dst.join(name))?;
        count += 1;
        bytes += entry.metadata().map(|m| m.len()).unwrap_or(0);
    }
    Ok((count, bytes))
}

fn read_meta(dir: &Path) -> Option<RestorePoint> {
    let raw = std::fs::read_to_string(dir.join(META_FILE)).ok()?;
    serde_json::from_str(&raw).ok()
}

fn write_meta(dir: &Path, point: &RestorePoint) -> Result<()> {
    let raw = serde_json::to_vec_pretty(point)
        .map_err(|err| NimbusError::Invalid(format!("cannot serialize restore point: {err}")))?;
    crate::config::write_atomic(&dir.join(META_FILE), &raw)
}

/// Newest first.
fn collect(restore_dir: &Path) -> Vec<RestorePoint> {
    let Ok(entries) = std::fs::read_dir(restore_dir) else {
        return Vec::new();
    };
    let mut points: Vec<RestorePoint> = entries
        .flatten()
        .filter(|e| e.path().is_dir())
        .filter_map(|e| read_meta(&e.path()))
        .collect();
    points.sort_by_key(|p| std::cmp::Reverse(p.created_at));
    points
}

/// Deletes the oldest snapshots above [`MAX_POINTS`]. Best effort: a locked
/// folder must not fail the operation that triggered the prune.
fn prune(restore_dir: &Path) {
    let points = collect(restore_dir);
    if points.len() <= MAX_POINTS {
        return;
    }
    for point in points.into_iter().skip(MAX_POINTS) {
        let dir = restore_dir.join(&point.id);
        if let Err(err) = std::fs::remove_dir_all(&dir) {
            crate::nlog!("restore: cannot prune {dir:?} ({err})");
        }
    }
}

/// Takes a snapshot. Used both by the UI button and, with `automatic = true`,
/// by mod updates and pack installs before they touch anything.
pub fn snapshot_blocking(
    mods_dir: &Path,
    restore_dir: &Path,
    label: &str,
    automatic: bool,
) -> Result<RestorePoint> {
    let now = chrono::Local::now();
    let mut id = now.format("%Y%m%d-%H%M%S").to_string();
    // Two snapshots inside the same second would collide on the folder name.
    if restore_dir.join(&id).exists() {
        let mut bump = now;
        while restore_dir.join(&id).exists() {
            bump += chrono::Duration::seconds(1);
            id = bump.format("%Y%m%d-%H%M%S").to_string();
        }
    }

    let dir = restore_dir.join(&id);
    let files_dir = dir.join("mods");
    let (mod_count, size_bytes) = copy_flat(mods_dir, &files_dir)?;

    let point = RestorePoint {
        id,
        label: if label.trim().is_empty() {
            "Снимок".to_string()
        } else {
            label.trim().to_string()
        },
        created_at: now.timestamp(),
        mod_count,
        size_bytes,
        automatic,
    };
    write_meta(&dir, &point)?;
    prune(restore_dir);
    Ok(point)
}

/// Convenience wrapper for other command modules (mod updates, pack install).
pub async fn auto_snapshot(instance_id: &str, label: &str) -> Result<RestorePoint> {
    let (mods_dir, restore_dir) = dirs(instance_id)?;
    let label = label.to_string();
    tokio::task::spawn_blocking(move || snapshot_blocking(&mods_dir, &restore_dir, &label, true))
        .await
        .map_err(|err| NimbusError::Invalid(format!("snapshot task failed: {err}")))?
}

#[tauri::command]
pub async fn create_restore_point(instance_id: String, label: String) -> Result<RestorePoint> {
    let (mods_dir, restore_dir) = dirs(&instance_id)?;
    tokio::task::spawn_blocking(move || snapshot_blocking(&mods_dir, &restore_dir, &label, false))
        .await
        .map_err(|err| NimbusError::Invalid(format!("snapshot task failed: {err}")))?
}

#[tauri::command]
pub async fn list_restore_points(instance_id: String) -> Result<Vec<RestorePoint>> {
    let (_, restore_dir) = dirs(&instance_id)?;
    tokio::task::spawn_blocking(move || collect(&restore_dir))
        .await
        .map_err(|err| NimbusError::Invalid(format!("list task failed: {err}")))
}

/// Rolls the `mods` folder back to a snapshot.
///
/// The current state is snapshotted first: a rollback is itself a destructive
/// action, and a user who picks the wrong point must not lose the working set
/// they had a second ago.
#[tauri::command]
pub async fn apply_restore_point(instance_id: String, point_id: String) -> Result<RestorePoint> {
    validate_point_id(&point_id)?;
    let (mods_dir, restore_dir) = dirs(&instance_id)?;

    tokio::task::spawn_blocking(move || {
        let source = restore_dir.join(&point_id);
        let Some(point) = read_meta(&source) else {
            return Err(NimbusError::Invalid(format!(
                "Точка восстановления {point_id} не найдена"
            )));
        };

        snapshot_blocking(&mods_dir, &restore_dir, "Перед откатом", true)?;

        // Clear only top-level files, mirroring what the snapshot captured.
        if let Ok(entries) = std::fs::read_dir(&mods_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() {
                    let _ = std::fs::remove_file(path);
                }
            }
        }
        copy_flat(&source.join("mods"), &mods_dir)?;
        Ok(point)
    })
    .await
    .map_err(|err| NimbusError::Invalid(format!("restore task failed: {err}")))?
}

#[tauri::command]
pub async fn delete_restore_point(instance_id: String, point_id: String) -> Result<()> {
    validate_point_id(&point_id)?;
    let (_, restore_dir) = dirs(&instance_id)?;
    tokio::task::spawn_blocking(move || {
        let dir = restore_dir.join(&point_id);
        if dir.exists() {
            std::fs::remove_dir_all(&dir)?;
        }
        Ok(())
    })
    .await
    .map_err(|err| NimbusError::Invalid(format!("delete task failed: {err}")))?
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn point_ids_reject_traversal() {
        assert!(validate_point_id("20260801-231500").is_ok());
        assert!(validate_point_id("../../etc").is_err());
        assert!(validate_point_id("20260801_231500").is_err());
        assert!(validate_point_id("20260801-23150").is_err());
    }
}
